services:
  postgres:
    image: postgres:16
    container_name: fleetcom-postgres
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: mudar123
      POSTGRES_DB: fleetcom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Liga o volume persistente à pasta onde o postgree grava o banco.

  Fleetcom-api:
    build:
      context: ./Fleetcom-api
      dockerfile: Dockerfile.dev
    container_name: Fleetcom-api
    env_file:
      - ./Fleetcom-api/.env
    ports:
      - "3000:3000"
    volumes:
      - ./Fleetcom-api:/app # código atualiza em tempo real!
      - /app/node_modules # mantém node_modules na sobrescrita (volume anônimo)
    depends_on:
      - postgres

  Fleetcom-app:
    build:
      context: ./Fleetcom-app
      dockerfile: Dockerfile.dev
    container_name: Fleetcom-app
    ports:
      - "4200:4200"
    volumes:
      - ./Fleetcom-app:/app
      - /app/node_modules
    depends_on:
      - Fleetcom-api

volumes:
  postgres_data: # Volume nomeado persistente para salvar os dados do MongoDB
