services:
  postgres:
    image: postgres:16
    container_name: fleetcom-postgres
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: mudar123
      POSTGRES_DB: fleetcom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  Fleetcom-api:
    build: ./Fleetcom-api
    container_name: Fleetcom-api
    env_file:
      - ./Fleetcom-api/.env
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  Fleetcom-app:
    build:
      context: ./Fleetcom-app
      dockerfile: Dockerfile
    container_name: Fleetcom-app
    ports:
      - "4200:80"
    depends_on:
      - Fleetcom-api


volumes:
  postgres_data:
