services:
  mongo:
    image: mongo:7.0
    container_name: Fleetcom-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  Fleetcom-api:
    build: ./Fleetcom-api
    container_name: Fleetcom-api
    env_file:
      - ./Fleetcom-api/.env
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  Fleetcom-app:
    build:
      context: ./Fleetcom-app
      dockerfile: Dockerfile
    container_name: Fleetcom-app
    ports:
      - "4200:80"
    depends_on:
      - Fleetcom-api


volumes:
  mongo_data:
